//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBusValidator.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardUpdate
    {
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Changed { get; set; }
        public long ChangedEpoch { get; set; }
        public string CardEsn { get; set; }
        public string CustomerCode { get; set; }
        public int Status { get; set; }
        public string Expiry { get; set; }
        public bool IsCompleted { get; set; }
    }
}
