//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBusValidator.DataProvider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EBusValidatorContext : DbContext
    {
        public EBusValidatorContext()
            : base("name=EBusValidatorContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardUpdate> CardUpdates { get; set; }
        public virtual DbSet<GpsTracking> GpsTrackings { get; set; }
        public virtual DbSet<Smartcard> Smartcards { get; set; }
        public virtual DbSet<SmartcardGuardian> SmartcardGuardians { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Validator> Validators { get; set; }
    }
}
