//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBusValidator.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartcardGuardian
    {
        public int ID { get; set; }
        public Nullable<int> SmartCardID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string RelationShip { get; set; }
        public string Cellphone { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateOn { get; set; }
    
        public virtual Smartcard Smartcard { get; set; }
    }
}
