//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBusValidator.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Validator
    {
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public int BusNumber { get; set; }
        public string CustomerCode { get; set; }
        public string ApiToken { get; set; }
        public long LastUpdateEpoch { get; set; }
    }
}
